### ISSUE TITLE
[BUG] Creating content not in default language, having title field translatable, results in no slug in default language after 'Save'

### ISSUE THREAD

**Issue by sbonardt** [BoltTranslate/Translate#114]
I have two languages on my Bolt install, English and Dutch (EN and NL). It works like a charm, and I have implemented Translate on multiple sites. However, I feel I now have encountered a bug:

When going to the admin section in the NL language (not the default) and creating a new piece of content, this gets me to the creating-new-piece-of-content-page and the lang selector isn't present so I am creating content in NL (not the default! lang) The title is translatable, so when hit SAVE the NL version gets saved properly, slug is there in the NL version. The EN version however doesn't get a slug, as the slug gets derived from the title and the title is translatable and therefore not set in the default ENG instance of the content.

As the slug is not set, going to the listing page in the bolt backend for the base language results in a error in bolt's default/base "base_listing.twig" template as the slugs aren't set for the particular (EN) pieces of content.

It does however work like a charm when creating new content in the base language. So it seems a problem only when creating new content in any language other than the default.

Details
-------

 - Translate Version: 4.0.5
 - Install type: Extension Repository
 - Bolt Version: 3.2.10
 - PHP version: [ 5.4 | 5.5 | 5.6 | 7.0 ]
 - Used webserver: [ Apache ]

![screen shot 2017-04-12 at 11 08 45](https://cloud.githubusercontent.com/assets/5597447/24950143/46e8616a-1f70-11e7-84ec-9397b5639dfe.png)
![screen shot 2017-04-12 at 11 09 00](https://cloud.githubusercontent.com/assets/5597447/24950144/473b8034-1f70-11e7-9360-73ab8391eec4.png)
![screen shot 2017-04-12 at 11 09 10](https://cloud.githubusercontent.com/assets/5597447/24950141/46e52784-1f70-11e7-99ff-5fe781ad3a9f.png)
![screen shot 2017-04-12 at 11 09 44](https://cloud.githubusercontent.com/assets/5597447/24950142/46e73db2-1f70-11e7-83ba-8c8058869784.png)

**Comment by SahAssar** [comment]
Hmm. creating a new record in a non-default locale should not be possible, I think this bug was introduced somewhere during 4.0...

**Comment by SahAssar** [comment]
Closing, I'm pretty sure that this is fixed so that it requires a record in the default locale first, lemme know if that isn't the case :)
