### ISSUE TITLE
[??] Translatable is misspelled

### ISSUE THREAD

**Issue by lenvanessen** [BoltTranslate/Translate#135]
is_translateable is misspelled, should be is_translatable

**Comment by SahAssar** [comment]
Yeah, I should fix that so that it accepts both and remove the misspelling in the next major... Or keep it around as a homage to the misspelling of referer in the HTTP spec :D

**Comment by lenvanessen** [comment]
Our add both for now? Change the docs and the `is_translatable`, and write a small part in the config that changes the old spelling on the fly?

**Comment by SahAssar** [comment]
Yeah, that was what I meant. Accept both now, and remove the misspelling in the next major.
