### ISSUE TITLE
Suggestion: just `translate: true`

### ISSUE THREAD

**Issue by Puddingboy** [BoltTranslate/Translate#159]
is_translateable: true, translatable: true...

those words must seem like horror to the dyslexic.

i propose:
`translate: true`

It's simple, it's phonetic, it's beautiful...
Just throwing it out there :)

*note: please take it with a grain of salt. Yesterday I spend half my morning checking my twig syntax to look for any quirks. Turns out, I just misspelled translatable. Yup I should read and write better.

If you enjoy this idea, just let me know and I'll do a PR to add translate to the list.

**Comment by SahAssar** [comment]
:-1: we just changed it to translatable and that looks better when placed together with other options like `sortable`
