### ISSUE TITLE
[BUG] Ghost Content in empty locales

### ISSUE THREAD

**Issue by Matthewbeck75** [BoltTranslate/Translate#167]
When creating a new record, then filling out translatable fields in the first (default) locale, then saving, then switching to a different locale (locale 2), the content you just entered will appear as if you are still on the first locale.

Pressing save immediately here will permanently save all of the data to locale 2.

While this is a bug, it can be somewhat useful to fill a locale with a copy of the data from the default one. Could perhaps a 'copy from locale x' drop down be implemented? 

Details
-------

 - Translate Version: [ 4.1.1 ]
 - Install type: [ Extension Repository ]
 - Bolt Version: [ 3.4.8 ]
 - PHP version: [  7.0 ]
 - Used webserver: [ Nginx ] 1.10  ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

 1. **Bug summary**: Switching to a locale void of data will show data from the default locale. Pressing save copies the data across. 
 2. **Specifics**: Bolt installed through file upload. Tested on Chrome Version 64.0.3282.186 and Firefox 58.0.2
 3. **Steps to reproduce**: Have at least 2 locales and a contenttype with translatable fields. Create a new record and fill out fields for locale 1. Save and switch to locale 2. All translatable fields should be filled out.
 4. **Expected result**: Translatable fields should be empty in locale 2.
 5. **Actual result**: Content from locale 1 is shown while in locale 2.

**Comment by SahAssar** [comment]
Any field not set has a fallback to the default locale, that is how it was designed. I'd be happy to merge a PR that makes this optional, but right now it isn't.
