### ISSUE TITLE
[BUG] Record locale returns 404 unless save has been pressed inside backend

### ISSUE THREAD

**Issue by Matthewbeck75** [BoltTranslate/Translate#168]
This ties in closely to #167.

When trying to access a page on a specific locale, a 404 is given if that locale has not had an entry saved in the back end. 

Details
-------

    Translate Version: [ 4.1.1 ]
    Install type: [ Extension Repository ]
    Bolt Version: [ 3.4.8 ]
    PHP version: [ 7.0 ]
    Used webserver: [ Nginx ] 1.10 ]

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

 1. **Bug summary**: Unless a record's locale has been entered on the back end and had save pressed, even if with no fields filled, it will 404 when trying to access it. 
 2. **Specifics**: Bolt installed through file upload. Tested on Chrome Version 64.0.3282.186 and Firefox 58.0. Shows the public 404 page.
 3. **Steps to reproduce**: Create a contenttype with at least 2 locales. Create a new record, enter data and press save. Do not switch to the second locale. Now, visit the page (locale 1) and change the URL to visit locale 2, which we did not edit. The page will 404
 4. **Expected result**: The record to show, with all translatable content empty.
 5. **Actual result**: 404 page, with no error messages.

**Comment by SahAssar** [comment]
Well, the page isn't there unless it has been saved in that locale? I'm not sure how any other result would make sense. Closing for now, feel free to reopen or discuss further.
