### ISSUE TITLE
[RFC] Fallback on missing content

### ISSUE THREAD

**Issue by madc** [BoltTranslate/Translate#65]
There have been suggestions regarding this by @Puddingboy and @evertalbers in #16. I have the feeling, that this is a longer topic, so I'm moving it here.

Currently, when creating a new record for a translatable contenttype, fields can only be populated for the default locale. Other locales are populated empty. (Am I right in assuming this, @SahAssar?)
At this point, if the website is opened in frontend with other than the default locale, the page is shown without values.

Here's my take on this:

At some point, someone will request, to be able to create a record in other than the default locale. And leave the default one empty. I'm not sure, if we should support this, as it makes the whole fallback thing even more complicated.

Also, if this is possible, we should make the `Status` field of a content type translatable by default for translatable contenttypes. This would allow an editor to decide, when content is ready to be published. 

Then regarding fallback, there are a couple of strategies, on how to handle this. From the top of my head:
- Fallback to default locale, if field is empty
- Fallback to default locale record, if fields are empty
- Still show the empty values
- Show a 404 or redirect to startpage
- Show a message (i.e. Not translation available, switch to [link to default locale])
## Real live example

I have a website, that also features translatable blog posts (DE as default, EN). Every post will first be written in german and then eventually translated.

The best possible outcome in my opinion would be to show the german content as long as the translation is missing. Maybe, show a little message on top, that this is not available in english atm.
It would behave this way, as long, as the `Status` for this language is not set to `Published`.

Please feel free to discuss and also bring your arguments from #16 again.

**Comment by SahAssar** [comment]
> Currently, when creating a new record for a translatable contenttype, fields can only be populated for the default locale. Other locales are populated empty. (Am I right in assuming this, @SahAssar?)

Well, not really. It currently does not fill the other locales, and does not fill the other locales slugs, so if `translate_slugs` is on it should 404 in other locales if the record has not been saved in that locale.

To allow for records in only non-default locales all we need to do is to remove this line: https://github.com/AnimalDesign/bolt-translate/blob/master/templates/fields/_locale.twig#L21 but those records would appear empty in the backend until one goes to edit them in the correct locale.

Personally I don't think we should display fallback content. Many sites will want to just have part of their site available in a certain language and displaying fallback would create many weird UX situations there. Besides that it might lead to duplicate content issues in search engines... If a record is not available in a locale it should just 404 and not be displayed in menus/listings IMO.

**Comment by madc** [comment]
I see. I've been thinking more about this and I agree. You make a valid point. It is agreed then, no fallback.

But, as you mentioned, we need to hide untranslated records from menus/listings. Do you think, this is much work?

**Comment by SahAssar** [comment]
Some, yes... We will need to modify the storage queries so that they check for a slug/status in the locale, but the structure in the database is already prepared for it (the locale slug field is broken out from the rest of the data) so it should be possible to do in a patch release.

**Comment by Puddingboy** [comment]
I will kinda stick to what I said before, I think it would be a good idea to be able to edit the default treatment of empty values from a yml config file. To top it off, you could implement a way on the backend as a UI element to overturn it if needed for specific records.

I think a good placement for such a UI element would be on a page(below the TL tabs) or in the meta. Could be something like this (the [] being select boxes):
```
translations:
NL : [offline(for lack of better word)] <- this option has been set
FR : [display native(default)]
```
English could be the default language here so it would not be shown.
so now you could have the option for each translation to display or be scratched from visitor access.

Not sure if this is a bad idea, but this was my line of thinking.

**Comment by SahAssar** [comment]
Spring cleaning, hopefully we can do this when we actually separate the tables and don't rely on the "default locale" holding all the data.
